In [2]:
import pandas as pd

# 1. Read in your CSV (make sure path is correct)
df = pd.read_csv('Anthropic_Sonnet35_full_results.csv')

# 2. (Optional) if you only want test‐split rows
df = df[df['split'] == 'test']

# 3. Grab the model name from the 'llm' column
model_name = df['llm'].iloc[0]

# 4. Get a sorted list of subjects so our rows stay in a consistent order
subjects = sorted(df['subject'].unique())

# 5. Loop over each language and sum up token counts
for lang in sorted(df['language'].unique()):
    df_lang = df[df['language'] == lang]

    # 5a. Sum tokens by subject
    subj_tokens = df_lang.groupby('subject')['num_tokens'].sum()

    # 5b. Build a DataFrame and name its column after the model
    table = subj_tokens.to_frame(name=model_name)

    # 5c. Compute the overall total‐tokens for this language
    total_tokens = df_lang['num_tokens'].sum()
    table.loc[f"Total {lang}"] = total_tokens

    # 5d. Reorder so the Total row sits at the top
    table = table.reindex([f"Total {lang}"] + subjects)

    # 5e. Print out a nice Markdown table
    print(f"\n### Token Counts for {lang} ({model_name})\n")
    print(table.to_markdown())

### Token Counts for amh (Anthropic/claude-3-5-sonnet-20241022)

| subject                    |   Anthropic/claude-3-5-sonnet-20241022 |
|:---------------------------|---------------------------------------:|
| Total amh                  |                                  99508 |
| elementary_mathematics     |                                  12001 |
| global_facts               |                                  14439 |
| high_school_geography      |                                  15577 |
| high_school_microeconomics |                                  24535 |
| international_law          |                                  32956 |

### Token Counts for eng (Anthropic/claude-3-5-sonnet-20241022)

| subject                    |   Anthropic/claude-3-5-sonnet-20241022 |
|:---------------------------|---------------------------------------:|
| Total eng                  |                                  30367 |
| elementary_mathematics     |                                   5733 |
| global_facts               |                                   4913 |
| high_school_geography      |                                   4295 |
| high_school_microeconomics |                                   6762 |
| international_law          |                                   8664 |

### Token Counts for ewe (Anthropic/claude-3-5-sonnet-20241022)

| subject                    |   Anthropic/claude-3-5-sonnet-20241022 |
|:---------------------------|---------------------------------------:|
| Total ewe                  |                                  84161 |
| elementary_mathematics     |                                   9326 |
| global_facts               |                                  11820 |
| high_school_geography      |                                  10783 |
| high_school_microeconomics |                                  22176 |
| international_law          |                                  30056 |

### Token Counts for fra (Anthropic/claude-3-5-sonnet-20241022)

| subject                    |   Anthropic/claude-3-5-sonnet-20241022 |
|:---------------------------|---------------------------------------:|
| Total fra                  |                                  46951 |
| elementary_mathematics     |                                   7131 |
| global_facts               |                                   7133 |
| high_school_geography      |                                   7251 |
| high_school_microeconomics |                                  10837 |
| international_law          |                                  14599 |

### Token Counts for hau (Anthropic/claude-3-5-sonnet-20241022)

| subject                    |   Anthropic/claude-3-5-sonnet-20241022 |
|:---------------------------|---------------------------------------:|
| Total hau                  |                                  57701 |
| elementary_mathematics     |                                   7987 |
| global_facts               |                                   8140 |
| high_school_geography      |                                   9047 |
| high_school_microeconomics |                                  12650 |
| international_law          |                                  19877 |

### Token Counts for ibo (Anthropic/claude-3-5-sonnet-20241022)

| subject                    |   Anthropic/claude-3-5-sonnet-20241022 |
|:---------------------------|---------------------------------------:|
| Total ibo                  |                                  68828 |
| elementary_mathematics     |                                   9785 |
| global_facts               |                                   9673 |
| high_school_geography      |                                  10222 |
| high_school_microeconomics |                                  17896 |
| international_law          |                                  21252 |

### Token Counts for kin (Anthropic/claude-3-5-sonnet-20241022)

| subject                    |   Anthropic/claude-3-5-sonnet-20241022 |
|:---------------------------|---------------------------------------:|
| Total kin                  |                                  61299 |
| elementary_mathematics     |                                   7781 |
| global_facts               |                                   9079 |
| high_school_geography      |                                   9751 |
| high_school_microeconomics |                                  14829 |
| international_law          |                                  19859 |

### Token Counts for lin (Anthropic/claude-3-5-sonnet-20241022)

| subject                    |   Anthropic/claude-3-5-sonnet-20241022 |
|:---------------------------|---------------------------------------:|
| Total lin                  |                                  49502 |
| elementary_mathematics     |                                   7373 |
| global_facts               |                                   7445 |
| high_school_geography      |                                   7672 |
| high_school_microeconomics |                                  11254 |
| international_law          |                                  15758 |

### Token Counts for lug (Anthropic/claude-3-5-sonnet-20241022)

| subject                    |   Anthropic/claude-3-5-sonnet-20241022 |
|:---------------------------|---------------------------------------:|
| Total lug                  |                                  73782 |
| elementary_mathematics     |                                   8886 |
| global_facts               |                                   9762 |
| high_school_geography      |                                  11125 |
| high_school_microeconomics |                                  20658 |
| international_law          |                                  23351 |

### Token Counts for orm (Anthropic/claude-3-5-sonnet-20241022)

| subject                    |   Anthropic/claude-3-5-sonnet-20241022 |
|:---------------------------|---------------------------------------:|
| Total orm                  |                                  62795 |
| elementary_mathematics     |                                   8582 |
| global_facts               |                                   9172 |
| high_school_geography      |                                  10262 |
| high_school_microeconomics |                                  14584 |
| international_law          |                                  20195 |

### Token Counts for sna (Anthropic/claude-3-5-sonnet-20241022)

| subject                    |   Anthropic/claude-3-5-sonnet-20241022 |
|:---------------------------|---------------------------------------:|
| Total sna                  |                                  56936 |
| elementary_mathematics     |                                   7597 |
| global_facts               |                                   8396 |
| high_school_geography      |                                   8381 |
| high_school_microeconomics |                                  15125 |
| international_law          |                                  17437 |

### Token Counts for sot (Anthropic/claude-3-5-sonnet-20241022)

| subject                    |   Anthropic/claude-3-5-sonnet-20241022 |
|:---------------------------|---------------------------------------:|
| Total sot                  |                                  54611 |
| elementary_mathematics     |                                   8098 |
| global_facts               |                                   8378 |
| high_school_geography      |                                   7751 |
| high_school_microeconomics |                                  13515 |
| international_law          |                                  16869 |

### Token Counts for swa (Anthropic/claude-3-5-sonnet-20241022)

| subject                    |   Anthropic/claude-3-5-sonnet-20241022 |
|:---------------------------|---------------------------------------:|
| Total swa                  |                                  54621 |
| elementary_mathematics     |                                   7905 |
| global_facts               |                                   8134 |
| high_school_geography      |                                   8711 |
| high_school_microeconomics |                                  12742 |
| international_law          |                                  17129 |

### Token Counts for twi (Anthropic/claude-3-5-sonnet-20241022)

| subject                    |   Anthropic/claude-3-5-sonnet-20241022 |
|:---------------------------|---------------------------------------:|
| Total twi                  |                                  78578 |
| elementary_mathematics     |                                  10489 |
| global_facts               |                                  10565 |
| high_school_geography      |                                  13172 |
| high_school_microeconomics |                                  19192 |
| international_law          |                                  25160 |

### Token Counts for wol (Anthropic/claude-3-5-sonnet-20241022)

| subject                    |   Anthropic/claude-3-5-sonnet-20241022 |
|:---------------------------|---------------------------------------:|
| Total wol                  |                                  64064 |
| elementary_mathematics     |                                   8070 |
| global_facts               |                                   9249 |
| high_school_geography      |                                   9489 |
| high_school_microeconomics |                                  15927 |
| international_law          |                                  21329 |

### Token Counts for xho (Anthropic/claude-3-5-sonnet-20241022)

| subject                    |   Anthropic/claude-3-5-sonnet-20241022 |
|:---------------------------|---------------------------------------:|
| Total xho                  |                                  59619 |
| elementary_mathematics     |                                   8331 |
| global_facts               |                                   9286 |
| high_school_geography      |                                   8910 |
| high_school_microeconomics |                                  13883 |
| international_law          |                                  19209 |

### Token Counts for yor (Anthropic/claude-3-5-sonnet-20241022)

| subject                    |   Anthropic/claude-3-5-sonnet-20241022 |
|:---------------------------|---------------------------------------:|
| Total yor                  |                                  97539 |
| elementary_mathematics     |                                  11774 |
| global_facts               |                                  14173 |
| high_school_geography      |                                  16092 |
| high_school_microeconomics |                                  23934 |
| international_law          |                                  31566 |

### Token Counts for zul (Anthropic/claude-3-5-sonnet-20241022)

| subject                    |   Anthropic/claude-3-5-sonnet-20241022 |
|:---------------------------|---------------------------------------:|
| Total zul                  |                                  58403 |
| elementary_mathematics     |                                   8497 |
| global_facts               |                                   8710 |
| high_school_geography      |                                   8800 |
| high_school_microeconomics |                                  13704 |
| international_law          |                                  18692 |

In [4]:
import pandas as pd
import glob

# 1. Read & combine all model CSVs
all_files = glob.glob('*_full_results.csv')
dfs = []
for fn in all_files:
    df = pd.read_csv(fn)
    # filter to test‐split if you only want evaluation tokens
    df = df[df['split']=='test']
    dfs.append(df)
df_all = pd.concat(dfs, ignore_index=True)

# 2. Prepare lists
languages = sorted(df_all['language'].unique())
subjects  = sorted(df_all['subject'].unique())

# 3. Loop through each language
for lang in languages:
    df_lang = df_all[df_all['language'] == lang]
    
    # 3a. Total token count per model
    total_tok = df_lang.groupby('llm')['num_tokens'].sum()
    total_df  = pd.DataFrame(total_tok).T
    total_df.index = [f"Total {lang}"]
    
    # 3b. Per‐subject token count per model
    subj_tok = (df_lang
                .pivot_table(
                    index='subject',
                    columns='llm',
                    values='num_tokens',
                    aggfunc='sum',
                    fill_value=0
                )
               )
    
    # 3c. Combine rows and reorder so “Total” is first
    combined = pd.concat([total_df, subj_tok])
    combined = combined.reindex([f"Total {lang}"] + subjects)
    
    # 3d. Alphabetical column order
    combined = combined[sorted(combined.columns)]
    
    # 3e. Print Markdown table
    print(f"\n### Token Counts for {lang}\n")
    print(combined.to_markdown())

### Token Counts for amh

|                            |   Anthropic/claude-3-5-sonnet-20241022 |   CohereLabs/aya-23-35B |   Google/gemini-15-Pro-002 |   OpenAI/gpt-4o-2024-08-06 |   OpenAI/o1-preview-2024-09-12 |   Qwen/Qwen2.5-32B |   deepseek-ai/DeepSeek-R1 |   deepseek-ai/DeepSeek-V3-0324 |   meta-llama/Llama-3.1-405B |   microsoft/phi-4 |   mistralai/Pixtral-12B-2409 |
|:---------------------------|---------------------------------------:|------------------------:|---------------------------:|---------------------------:|-------------------------------:|-------------------:|--------------------------:|-------------------------------:|----------------------------:|------------------:|-----------------------------:|
| Total amh                  |                                  99508 |                  146228 |                      75154 |                     133085 |                         133085 |              97638 |                    138175 |                         138175 |                      174187 |            174308 |                       176728 |
| elementary_mathematics     |                                  12001 |                   16304 |                       9559 |                      14323 |                          14323 |              11823 |                     14901 |                          14901 |                       18123 |             18152 |                        19074 |
| global_facts               |                                  14439 |                   20235 |                      11091 |                      18150 |                          18150 |              13922 |                     18753 |                          18753 |                       23317 |             23342 |                        24067 |
| high_school_geography      |                                  15577 |                   22847 |                      11331 |                      21104 |                          21104 |              14946 |                     21654 |                          21654 |                       27923 |             27950 |                        28146 |
| high_school_microeconomics |                                  24535 |                   35897 |                      17681 |                      32548 |                          32548 |              23525 |                     34377 |                          34377 |                       42871 |             42898 |                        43197 |
| international_law          |                                  32956 |                   50945 |                      25492 |                      46960 |                          46960 |              33422 |                     48490 |                          48490 |                       61953 |             61966 |                        62244 |

### Token Counts for eng

|                            |   Anthropic/claude-3-5-sonnet-20241022 |   CohereLabs/aya-23-35B |   Google/gemini-15-Pro-002 |   OpenAI/gpt-4o-2024-08-06 |   OpenAI/o1-preview-2024-09-12 |   Qwen/Qwen2.5-32B |   deepseek-ai/DeepSeek-R1 |   deepseek-ai/DeepSeek-V3-0324 |   meta-llama/Llama-3.1-405B |   microsoft/phi-4 |   mistralai/Pixtral-12B-2409 |
|:---------------------------|---------------------------------------:|------------------------:|---------------------------:|---------------------------:|-------------------------------:|-------------------:|--------------------------:|-------------------------------:|----------------------------:|------------------:|-----------------------------:|
| Total eng                  |                                  30367 |                   26259 |                      26119 |                      24963 |                          24963 |              26458 |                     24919 |                          24919 |                       25055 |             25062 |                        27634 |
| elementary_mathematics     |                                   5733 |                    5229 |                       5206 |                       4493 |                           4493 |               5230 |                      4482 |                           4482 |                        4502 |              4502 |                         5456 |
| global_facts               |                                   4913 |                    4558 |                       4554 |                       4026 |                           4026 |               4564 |                      4024 |                           4024 |                        4029 |              4029 |                         4784 |
| high_school_geography      |                                   4295 |                    3318 |                       3305 |                       3352 |                           3352 |               3392 |                      3317 |                           3317 |                        3366 |              3369 |                         3588 |
| high_school_microeconomics |                                   6762 |                    5651 |                       5588 |                       5596 |                           5596 |               5663 |                      5607 |                           5607 |                        5626 |              5626 |                         5941 |
| international_law          |                                   8664 |                    7503 |                       7466 |                       7496 |                           7496 |               7609 |                      7489 |                           7489 |                        7532 |              7536 |                         7865 |

### Token Counts for ewe

|                            |   Anthropic/claude-3-5-sonnet-20241022 |   CohereLabs/aya-23-35B |   Google/gemini-15-Pro-002 |   OpenAI/gpt-4o-2024-08-06 |   OpenAI/o1-preview-2024-09-12 |   Qwen/Qwen2.5-32B |   deepseek-ai/DeepSeek-R1 |   deepseek-ai/DeepSeek-V3-0324 |   meta-llama/Llama-3.1-405B |   microsoft/phi-4 |   mistralai/Pixtral-12B-2409 |
|:---------------------------|---------------------------------------:|------------------------:|---------------------------:|---------------------------:|-------------------------------:|-------------------:|--------------------------:|-------------------------------:|----------------------------:|------------------:|-----------------------------:|
| Total ewe                  |                                  84161 |                   64533 |                      59897 |                      61634 |                          61634 |              64178 |                     66072 |                          66072 |                       71182 |             74562 |                        75331 |
| elementary_mathematics     |                                   9326 |                    7734 |                       7390 |                       6951 |                           6951 |               7622 |                      7231 |                           7231 |                        7550 |              7890 |                         8674 |
| global_facts               |                                  11820 |                    9357 |                       8758 |                       8619 |                           8619 |               9487 |                      9201 |                           9201 |                        9776 |             10299 |                        10910 |
| high_school_geography      |                                  10783 |                    7909 |                       7407 |                       7649 |                           7649 |               7909 |                      8237 |                           8237 |                        9055 |              9539 |                         9484 |
| high_school_microeconomics |                                  22176 |                   17133 |                      15794 |                      16785 |                          16785 |              16814 |                     17816 |                          17816 |                       19311 |             20143 |                        20095 |
| international_law          |                                  30056 |                   22400 |                      20548 |                      21630 |                          21630 |              22346 |                     23587 |                          23587 |                       25490 |             26691 |                        26168 |

### Token Counts for fra

|                            |   Anthropic/claude-3-5-sonnet-20241022 |   CohereLabs/aya-23-35B |   Google/gemini-15-Pro-002 |   OpenAI/gpt-4o-2024-08-06 |   OpenAI/o1-preview-2024-09-12 |   Qwen/Qwen2.5-32B |   deepseek-ai/DeepSeek-R1 |   deepseek-ai/DeepSeek-V3-0324 |   meta-llama/Llama-3.1-405B |   microsoft/phi-4 |   mistralai/Pixtral-12B-2409 |
|:---------------------------|---------------------------------------:|------------------------:|---------------------------:|---------------------------:|-------------------------------:|-------------------:|--------------------------:|-------------------------------:|----------------------------:|------------------:|-----------------------------:|
| Total fra                  |                                  46951 |                   34693 |                      35005 |                      33718 |                          33718 |              40751 |                     37724 |                          37724 |                       39825 |             39874 |                        35802 |
| elementary_mathematics     |                                   7131 |                    5812 |                       5775 |                       5078 |                           5078 |               6325 |                      5506 |                           5506 |                        5659 |              5662 |                         6040 |
| global_facts               |                                   7133 |                    5659 |                       5712 |                       5208 |                           5208 |               6438 |                      5629 |                           5629 |                        5931 |              5936 |                         5888 |
| high_school_geography      |                                   7251 |                    4804 |                       5025 |                       5027 |                           5027 |               5982 |                      5662 |                           5662 |                        6047 |              6062 |                         5132 |
| high_school_microeconomics |                                  10837 |                    7765 |                       7659 |                       7638 |                           7638 |               9054 |                      8777 |                           8777 |                        9148 |              9154 |                         7933 |
| international_law          |                                  14599 |                   10653 |                      10834 |                      10767 |                          10767 |              12952 |                     12150 |                          12150 |                       13040 |             13060 |                        10809 |

### Token Counts for hau

|                            |   Anthropic/claude-3-5-sonnet-20241022 |   CohereLabs/aya-23-35B |   Google/gemini-15-Pro-002 |   OpenAI/gpt-4o-2024-08-06 |   OpenAI/o1-preview-2024-09-12 |   Qwen/Qwen2.5-32B |   deepseek-ai/DeepSeek-R1 |   deepseek-ai/DeepSeek-V3-0324 |   meta-llama/Llama-3.1-405B |   microsoft/phi-4 |   mistralai/Pixtral-12B-2409 |
|:---------------------------|---------------------------------------:|------------------------:|---------------------------:|---------------------------:|-------------------------------:|-------------------:|--------------------------:|-------------------------------:|----------------------------:|------------------:|-----------------------------:|
| Total hau                  |                                  57701 |                   48980 |                      45624 |                      40057 |                          40057 |              51587 |                     49973 |                          49973 |                       51604 |             52097 |                        52769 |
| elementary_mathematics     |                                   7987 |                    7050 |                       6771 |                       5753 |                           5753 |               7246 |                      6506 |                           6506 |                        6634 |              6671 |                         7473 |
| global_facts               |                                   8140 |                    7279 |                       6938 |                       5814 |                           5814 |               7630 |                      7007 |                           7007 |                        7205 |              7249 |                         7782 |
| high_school_geography      |                                   9047 |                    7133 |                       6594 |                       6003 |                           6003 |               7574 |                      7502 |                           7502 |                        7807 |              7874 |                         7834 |
| high_school_microeconomics |                                  12650 |                   10845 |                      10100 |                       8873 |                           8873 |              11675 |                     11446 |                          11446 |                       11734 |             11860 |                        11622 |
| international_law          |                                  19877 |                   16673 |                      15221 |                      13614 |                          13614 |              17462 |                     17512 |                          17512 |                       18224 |             18443 |                        18058 |

### Token Counts for ibo

|                            |   Anthropic/claude-3-5-sonnet-20241022 |   CohereLabs/aya-23-35B |   Google/gemini-15-Pro-002 |   OpenAI/gpt-4o-2024-08-06 |   OpenAI/o1-preview-2024-09-12 |   Qwen/Qwen2.5-32B |   deepseek-ai/DeepSeek-R1 |   deepseek-ai/DeepSeek-V3-0324 |   meta-llama/Llama-3.1-405B |   microsoft/phi-4 |   mistralai/Pixtral-12B-2409 |
|:---------------------------|---------------------------------------:|------------------------:|---------------------------:|---------------------------:|-------------------------------:|-------------------:|--------------------------:|-------------------------------:|----------------------------:|------------------:|-----------------------------:|
| Total ibo                  |                                  68828 |                   56647 |                      52752 |                      37737 |                          37737 |              56954 |                     55725 |                          55725 |                       55430 |             57267 |                        58645 |
| elementary_mathematics     |                                   9785 |                    8233 |                       7868 |                       5855 |                           5855 |               8322 |                      7614 |                           7614 |                        7601 |              7740 |                         8570 |
| global_facts               |                                   9673 |                    8318 |                       7853 |                       5870 |                           5870 |               8381 |                      7850 |                           7850 |                        7837 |              8064 |                         8651 |
| high_school_geography      |                                  10222 |                    8059 |                       7507 |                       5279 |                           5279 |               8173 |                      8000 |                           8000 |                        8122 |              8303 |                         8436 |
| high_school_microeconomics |                                  17896 |                   14427 |                      13353 |                       9429 |                           9429 |              14443 |                     14684 |                          14684 |                       14398 |             15092 |                        14887 |
| international_law          |                                  21252 |                   17610 |                      16171 |                      11304 |                          11304 |              17635 |                     17577 |                          17577 |                       17472 |             18068 |                        18101 |

### Token Counts for kin

|                            |   Anthropic/claude-3-5-sonnet-20241022 |   CohereLabs/aya-23-35B |   Google/gemini-15-Pro-002 |   OpenAI/gpt-4o-2024-08-06 |   OpenAI/o1-preview-2024-09-12 |   Qwen/Qwen2.5-32B |   deepseek-ai/DeepSeek-R1 |   deepseek-ai/DeepSeek-V3-0324 |   meta-llama/Llama-3.1-405B |   microsoft/phi-4 |   mistralai/Pixtral-12B-2409 |
|:---------------------------|---------------------------------------:|------------------------:|---------------------------:|---------------------------:|-------------------------------:|-------------------:|--------------------------:|-------------------------------:|----------------------------:|------------------:|-----------------------------:|
| Total kin                  |                                  61299 |                   52766 |                      51913 |                      44297 |                          44297 |              55816 |                     53917 |                          53917 |                       54046 |             54472 |                        55226 |
| elementary_mathematics     |                                   7781 |                    6957 |                       6799 |                       5778 |                           5778 |               7241 |                      6412 |                           6412 |                        6486 |              6521 |                         7308 |
| global_facts               |                                   9079 |                    7966 |                       7747 |                       6502 |                           6502 |               8393 |                      7765 |                           7765 |                        7803 |              7869 |                         8281 |
| high_school_geography      |                                   9751 |                    7876 |                       7757 |                       6891 |                           6891 |               8468 |                      8386 |                           8386 |                        8369 |              8453 |                         8459 |
| high_school_microeconomics |                                  14829 |                   12646 |                      12384 |                      10628 |                          10628 |              13491 |                     13252 |                          13252 |                       13368 |             13467 |                        13155 |
| international_law          |                                  19859 |                   17321 |                      17226 |                      14498 |                          14498 |              18223 |                     18102 |                          18102 |                       18020 |             18162 |                        18023 |

### Token Counts for lin


In [7]:
import pandas as pd
import glob

# find all of your ‘…_full_results.csv’ files
files = glob.glob('*_full_results.csv')

# accumulate tokenizer values
tokenizers = set()
for fn in files:
    df = pd.read_csv(fn, usecols=['tokenizer'])
    tokenizers.update(df['tokenizer'].dropna().unique())

# print them sorted
print("Unique tokenizers across all CSVs:")
for tok in sorted(tokenizers):
    print("-", tok)

Unique tokenizers across all CSVs:
- CohereLabs/aya-23-35B
- Qwen/Qwen2.5-32B
- anthropic/claude-3.5-sonnet
- deepseek-ai/DeepSeek-R1
- deepseek-ai/DeepSeek-V3-0324
- google/gemini-1.5-pro-002
- meta-llama/Llama-3.1-405B
- microsoft/phi-4
- mistralai/Pixtral-12B-2409
- openai/gpt-4o/o200k_base
- openai/o1-preview/o200k_base*

In [1]:
import pandas as pd
import glob

# 1) Read & concatenate all of your *_full_results.csv
csv_files = glob.glob("*_full_results.csv")
df = pd.concat([pd.read_csv(f) for f in csv_files], ignore_index=True)

# 2) Make the core pivot: (subject, language) × llm → sum(num_tokens)
pivot = (
    df
    .pivot_table(
        index=["subject", "language"],
        columns="llm",
        values="num_tokens",
        aggfunc="sum"
    )
)

# 3) Compute per‐subject subtotals
#    This gives a DataFrame indexed by subject, columns=llm
subs = df.groupby(["subject","llm"])["num_tokens"].sum().unstack(fill_value=0)

#  Build a MultiIndex for “(subject, All languages)”
sub_idx = pd.MultiIndex.from_product(
    [subs.index, ["All languages"]],
    names=["subject","language"]
)

subtotals = pd.DataFrame(
    data=subs.values,
    index=sub_idx,
    columns=subs.columns
)

# 4) Compute the grand total across every subject & language
grand = df.groupby("llm")["num_tokens"].sum()
grand_idx = pd.MultiIndex.from_tuples(
    [("All subjects", "")],
    names=["subject","language"]
)
grand_total = pd.DataFrame([grand.values], index=grand_idx, columns=grand.index)

# 5) Stitch them in order: for each subject, the languages then its subtotal,
#    then finally the overall total
out_frames = []
for subj in pivot.index.get_level_values("subject").unique():
    out_frames.append(pivot.loc[[subj]])                      # all (subj, lang) rows
    out_frames.append(subtotals.loc[subj:subj])               # the one subtotal row

out_frames.append(grand_total)

final = pd.concat(out_frames)

# 6) View or export
final

llm                                   Anthropic/claude-3-5-sonnet-20241022  \
subject                language
elementary_mathematics amh                                           12001
                       eng                                            5733
                       ewe                                            9326
                       fra                                            7131
                       hau                                            7987
...                                                                    ...
international_law      xho                                           19209
                       yor                                           31566
                       zul                                           18692
                       All languages                                373958
All subjects                                                       1159265

llm                                   CohereLabs/aya-23-35B  \
subject                language
elementary_mathematics amh                            16304
                       eng                             5229
                       ewe                             7734
                       fra                             5812
                       hau                             7050
...                                                     ...
international_law      xho                            16345
                       yor                            22277
                       zul                            15745
                       All languages                 329358
All subjects                                        1018523

llm                                   Google/gemini-15-Pro-002  \
subject                language
elementary_mathematics amh                                9559
                       eng                                5206
                       ewe                                7390
                       fra                                5775
                       hau                                6771
...                                                        ...
international_law      xho                               16249
                       yor                               20942
                       zul                               15432
                       All languages                    292721
All subjects                                            915028

llm                                   OpenAI/gpt-4o-2024-08-06  \
subject                language
elementary_mathematics amh                               14323
                       eng                                4493
                       ewe                                6951
                       fra                                5078
                       hau                                5753
...                                                        ...
international_law      xho                               13572
                       yor                               17762
                       zul                               12796
                       All languages                    286468
All subjects                                            876352

llm                                   OpenAI/o1-preview-2024-09-12  \
subject                language
elementary_mathematics amh                                   14323
                       eng                                    4493
                       ewe                                    6951
                       fra                                    5078
                       hau                                    5753
...                                                            ...
international_law      xho                                   13572
                       yor                                   17762
                       zul                                   12796
                       All languages                        286468
All subjects                                                876352

llm                                   Qwen/Qwen2.5-32B  \
subject                language
elementary_mathematics amh                       11823
                       eng                        5230
                       ewe                        7622
                       fra                        6325
                       hau                        7246
...                                                ...
international_law      xho                       17896
                       yor                       23593
                       zul                       17340
                       All languages            328851
All subjects                                   1017587

llm                                   deepseek-ai/DeepSeek-R1  \
subject                language
elementary_mathematics amh                              14901
                       eng                               4482
                       ewe                               7231
                       fra                               5506
                       hau                               6506
...                                                       ...
international_law      xho                              17797
                       yor                              24763
                       zul                              17036
                       All languages                   342758
All subjects                                          1032339

llm                                   deepseek-ai/DeepSeek-V3-0324  \
subject                language
elementary_mathematics amh                                   14901
                       eng                                    4482
                       ewe                                    7231
                       fra                                    5506
                       hau                                    6506
...                                                            ...
international_law      xho                                   17797
                       yor                                   24763
                       zul                                   17036
                       All languages                        342758
All subjects                                               1032339

llm                                   meta-llama/Llama-3.1-405B  \
subject                language
elementary_mathematics amh                                18123
                       eng                                 4502
                       ewe                                 7550
                       fra                                 5659
                       hau                                 6634
...                                                         ...
international_law      xho                                17577
                       yor                                23491
                       zul                                17012
                       All languages                     361698
All subjects                                            1085020

llm                                   microsoft/phi-4  \
subject                language
elementary_mathematics amh                      18152
                       eng                       4502
                       ewe                       7890
                       fra                       5662
                       hau                       6671
...                                               ...
international_law      xho                      17837
                       yor                      25672
                       zul                      17283
                       All languages           368050
All subjects                                  1103368

llm                                   mistralai/Pixtral-12B-2409
subject                language
elementary_mathematics amh                                 19074
                       eng                                  5456
                       ewe                                  8674
                       fra                                  6040
                       hau                                  7473
...                                                          ...
international_law      xho                                 17596
                       yor                                 24390
                       zul                                 16983
                       All languages                      360474
All subjects                                             1112784

[96 rows x 11 columns]

In [5]:
import pandas as pd

# 1) Lift the display limits:
pd.set_option("display.max_rows",    None)   # show all rows
pd.set_option("display.max_columns", None)   # show all columns
pd.set_option("display.width",       None)   # don’t wrap lines

# 2) If you already have `final` from the pivot/concat step:
display(final)

llm                                       Anthropic/claude-3-5-sonnet-20241022  \
subject                    language
elementary_mathematics     amh                                           12001
                           eng                                            5733
                           ewe                                            9326
                           fra                                            7131
                           hau                                            7987
                           ibo                                            9785
                           kin                                            7781
                           lin                                            7373
                           lug                                            8886
                           orm                                            8582
                           sna                                            7597
                           sot                                            8098
                           swa                                            7905
                           twi                                           10489
                           wol                                            8070
                           xho                                            8331
                           yor                                           11774
                           zul                                            8497
                           All languages                                155346
global_facts               amh                                           14439
                           eng                                            4913
                           ewe                                           11820
                           fra                                            7133
                           hau                                            8140
                           ibo                                            9673
                           kin                                            9079
                           lin                                            7445
                           lug                                            9762
                           orm                                            9172
                           sna                                            8396
                           sot                                            8378
                           swa                                            8134
                           twi                                           10565
                           wol                                            9249
                           xho                                            9286
                           yor                                           14173
                           zul                                            8710
                           All languages                                168467
high_school_geography      amh                                           15577
                           eng                                            4295
                           ewe                                           10783
                           fra                                            7251
                           hau                                            9047
                           ibo                                           10222
                           kin                                            9751
                           lin                                            7672
                           lug                                           11125
                           orm                                           10262
                           sna                                            8381
                           sot                                            7751
                           swa                                            8711
                           twi                                           13172
                           wol                                            9489
                           xho                                            8910
                           yor                                           16092
                           zul                                            8800
                           All languages                                177291
high_school_microeconomics amh                                           24535
                           eng                                            6762
                           ewe                                           22176
                           fra                                           10837
                           hau                                           12650
                           ibo                                           17896
                           kin                                           14829
                           lin                                           11254
                           lug                                           20658
                           orm                                           14584
                           sna                                           15125
                           sot                                           13515
                           swa                                           12742
                           twi                                           19192
                           wol                                           15927
                           xho                                           13883
                           yor                                           23934
                           zul                                           13704
                           All languages                                284203
international_law          amh                                           32956
                           eng                                            8664
                           ewe                                           30056
                           fra                                           14599
                           hau                                           19877
                           ibo                                           21252
                           kin                                           19859
                           lin                                           15758
                           lug                                           23351
                           orm                                           20195
                           sna                                           17437
                           sot                                           16869
                           swa                                           17129
                           twi                                           25160
                           wol                                           21329
                           xho                                           19209
                           yor                                           31566
                           zul                                           18692
                           All languages                                373958
All subjects                                                           1159265

llm                                       CohereLabs/aya-23-35B  \
subject                    language
elementary_mathematics     amh                            16304
                           eng                             5229
                           ewe                             7734
                           fra                             5812
                           hau                             7050
                           ibo                             8233
                           kin                             6957
                           lin                             6431
                           lug                             7907
                           orm                             7506
                           sna                             6763
                           sot                             7227
                           swa                             7074
                           twi                             8146
                           wol                             7337
                           xho                             7414
                           yor                             9265
                           zul                             7429
                           All languages                 139818
global_facts               amh                            20235
                           eng                             4558
                           ewe                             9357
                           fra                             5659
                           hau                             7279
                           ibo                             8318
                           kin                             7966
                           lin                             6557
                           lug                             8748
                           orm                             8042
                           sna                             7504
                           sot                             7586
                           swa                             7200
                           twi                             8134
                           wol                             8290
                           xho                             7886
                           yor                            10702
                           zul                             7639
                           All languages                 151660
high_school_geography      amh                            22847
                           eng                             3318
                           ewe                             7909
                           fra                             4804
                           hau                             7133
                           ibo                             8059
                           kin                             7876
                           lin                             5811
                           lug                             9023
                           orm                             8469
                           sna                             6750
                           sot                             6305
                           swa                             7024
                           twi                             9308
                           wol                             8007
                           xho                             7301
                           yor                            11428
                           zul                             7155
                           All languages                 148527
high_school_microeconomics amh                            35897
                           eng                             5651
                           ewe                            17133
                           fra                             7765
                           hau                            10845
                           ibo                            14427
                           kin                            12646
                           lin                             9442
                           lug                            17698
                           orm                            12599
                           sna                            13079
                           sot                            11806
                           swa                            10967
                           twi                            13794
                           wol                            14588
                           xho                            11970
                           yor                            17388
                           zul                            11465
                           All languages                 249160
international_law          amh                            50945
                           eng                             7503
                           ewe                            22400
                           fra                            10653
                           hau                            16673
                           ibo                            17610
                           kin                            17321
                           lin                            12788
                           lug                            20042
                           orm                            16896
                           sna                            15066
                           sot                            14780
                           swa                            14656
                           twi                            18353
                           wol                            19305
                           xho                            16345
                           yor                            22277
                           zul                            15745
                           All languages                 329358
All subjects                                            1018523

llm                                       Google/gemini-15-Pro-002  \
subject                    language
elementary_mathematics     amh                                9559
                           eng                                5206
                           ewe                                7390
                           fra                                5775
                           hau                                6771
                           ibo                                7868
                           kin                                6799
                           lin                                6376
                           lug                                7898
                           orm                                7338
                           sna                                6597
                           sot                                7010
                           swa                                6531
                           twi                                7999
                           wol                                7152
                           xho                                7334
                           yor                                8905
                           zul                                7382
                           All languages                    129890
global_facts               amh                               11091
                           eng                                4554
                           ewe                                8758
                           fra                                5712
                           hau                                6938
                           ibo                                7853
                           kin                                7747
                           lin                                6499
                           lug                                8528
                           orm                                7870
                           sna                                7294
                           sot                                7223
                           swa                                6559
                           twi                                7873
                           wol                                8091
                           xho                                7793
                           yor                               10157
                           zul                                7526
                           All languages                    138066
high_school_geography      amh                               11331
                           eng                                3305
                           ewe                                7407
                           fra                                5025
                           hau                                6594
                           ibo                                7507
                           kin                                7757
                           lin                                5863
                           lug                                8903
                           orm                                8150
                           sna                                6585
                           sot                                5963
                           swa                                6248
                           twi                                9336
                           wol                                7806
                           xho                                7166
                           yor                               10801
                           zul                                7027
                           All languages                    132774
high_school_microeconomics amh                               17681
                           eng                                5588
                           ewe                               15794
                           fra                                7659
                           hau                               10100
                           ibo                               13353
                           kin                               12384
                           lin                                9293
                           lug                               17315
                           orm                               12167
                           sna                               12487
                           sot                               11117
                           swa                                9817
                           twi                               13293
                           wol                               13784
                           xho                               11694
                           yor                               16425
                           zul                               11626
                           All languages                    221577
international_law          amh                               25492
                           eng                                7466
                           ewe                               20548
                           fra                               10834
                           hau                               15221
                           ibo                               16171
                           kin                               17226
                           lin                               12771
                           lug                               19716
                           orm                               16327
                           sna                               14714
                           sot                               13918

In [7]:
import pandas as pd
import glob

# 1) Read & concatenate
csv_files = glob.glob("*_full_results.csv")
df = pd.concat([pd.read_csv(f) for f in csv_files], ignore_index=True)

# 2) Pivot into a MultiIndex of (subject, language) × llm → sum(num_tokens)
final = (
    df
    .pivot_table(
        index=["subject", "language"],
        columns="llm",
        values="num_tokens",
        aggfunc="sum"
    )
    .sort_index()
)

# 3) (Optional) lift pandas display limits in Jupyter
pd.set_option("display.max_rows",    None)
pd.set_option("display.max_columns", None)
pd.set_option("display.width",       None)

# 4) Show it
display(final)

llm                                  Anthropic/claude-3-5-sonnet-20241022  \
subject                    language
elementary_mathematics     amh                                      12001
                           eng                                       5733
                           ewe                                       9326
                           fra                                       7131
                           hau                                       7987
                           ibo                                       9785
                           kin                                       7781
                           lin                                       7373
                           lug                                       8886
                           orm                                       8582
                           sna                                       7597
                           sot                                       8098
                           swa                                       7905
                           twi                                      10489
                           wol                                       8070
                           xho                                       8331
                           yor                                      11774
                           zul                                       8497
global_facts               amh                                      14439
                           eng                                       4913
                           ewe                                      11820
                           fra                                       7133
                           hau                                       8140
                           ibo                                       9673
                           kin                                       9079
                           lin                                       7445
                           lug                                       9762
                           orm                                       9172
                           sna                                       8396
                           sot                                       8378
                           swa                                       8134
                           twi                                      10565
                           wol                                       9249
                           xho                                       9286
                           yor                                      14173
                           zul                                       8710
high_school_geography      amh                                      15577
                           eng                                       4295
                           ewe                                      10783
                           fra                                       7251
                           hau                                       9047
                           ibo                                      10222
                           kin                                       9751
                           lin                                       7672
                           lug                                      11125
                           orm                                      10262
                           sna                                       8381
                           sot                                       7751
                           swa                                       8711
                           twi                                      13172
                           wol                                       9489
                           xho                                       8910
                           yor                                      16092
                           zul                                       8800
high_school_microeconomics amh                                      24535
                           eng                                       6762
                           ewe                                      22176
                           fra                                      10837
                           hau                                      12650
                           ibo                                      17896
                           kin                                      14829
                           lin                                      11254
                           lug                                      20658
                           orm                                      14584
                           sna                                      15125
                           sot                                      13515
                           swa                                      12742
                           twi                                      19192
                           wol                                      15927
                           xho                                      13883
                           yor                                      23934
                           zul                                      13704
international_law          amh                                      32956
                           eng                                       8664
                           ewe                                      30056
                           fra                                      14599
                           hau                                      19877
                           ibo                                      21252
                           kin                                      19859
                           lin                                      15758
                           lug                                      23351
                           orm                                      20195
                           sna                                      17437
                           sot                                      16869
                           swa                                      17129
                           twi                                      25160
                           wol                                      21329
                           xho                                      19209
                           yor                                      31566
                           zul                                      18692

llm                                  CohereLabs/aya-23-35B  \
subject                    language
elementary_mathematics     amh                       16304
                           eng                        5229
                           ewe                        7734
                           fra                        5812
                           hau                        7050
                           ibo                        8233
                           kin                        6957
                           lin                        6431
                           lug                        7907
                           orm                        7506
                           sna                        6763
                           sot                        7227
                           swa                        7074
                           twi                        8146
                           wol                        7337
                           xho                        7414
                           yor                        9265
                           zul                        7429
global_facts               amh                       20235
                           eng                        4558
                           ewe                        9357
                           fra                        5659
                           hau                        7279
                           ibo                        8318
                           kin                        7966
                           lin                        6557
                           lug                        8748
                           orm                        8042
                           sna                        7504
                           sot                        7586
                           swa                        7200
                           twi                        8134
                           wol                        8290
                           xho                        7886
                           yor                       10702
                           zul                        7639
high_school_geography      amh                       22847
                           eng                        3318
                           ewe                        7909
                           fra                        4804
                           hau                        7133
                           ibo                        8059
                           kin                        7876
                           lin                        5811
                           lug                        9023
                           orm                        8469
                           sna                        6750
                           sot                        6305
                           swa                        7024
                           twi                        9308
                           wol                        8007
                           xho                        7301
                           yor                       11428
                           zul                        7155
high_school_microeconomics amh                       35897
                           eng                        5651
                           ewe                       17133
                           fra                        7765
                           hau                       10845
                           ibo                       14427
                           kin                       12646
                           lin                        9442
                           lug                       17698
                           orm                       12599
                           sna                       13079
                           sot                       11806
                           swa                       10967
                           twi                       13794
                           wol                       14588
                           xho                       11970
                           yor                       17388
                           zul                       11465
international_law          amh                       50945
                           eng                        7503
                           ewe                       22400
                           fra                       10653
                           hau                       16673
                           ibo                       17610
                           kin                       17321
                           lin                       12788
                           lug                       20042
                           orm                       16896
                           sna                       15066
                           sot                       14780
                           swa                       14656
                           twi                       18353
                           wol                       19305
                           xho                       16345
                           yor                       22277
                           zul                       15745

llm                                  Google/gemini-15-Pro-002  \
subject                    language
elementary_mathematics     amh                           9559
                           eng                           5206
                           ewe                           7390
                           fra                           5775
                           hau                           6771
                           ibo                           7868
                           kin                           6799
                           lin                           6376
                           lug                           7898
                           orm                           7338
                           sna                           6597
                           sot                           7010
                           swa                           6531
                           twi                           7999
                           wol                           7152
                           xho                           7334
                           yor                           8905
                           zul                           7382
global_facts               amh                          11091
                           eng                           4554
                           ewe                           8758
                           fra                           5712
                           hau                           6938
                           ibo                           7853
                           kin                           7747
                           lin                           6499
                           lug                           8528
                           orm                           7870
                           sna                           7294
                           sot                           7223
                           swa                           6559
                           twi                           7873
                           wol                           8091
                           xho                           7793
                           yor                          10157
                           zul                           7526
high_school_geography      amh                          11331
                           eng                           3305
                           ewe                           7407
                           fra                           5025
                           hau                           6594
                           ibo                           7507
                           kin                           7757
                           lin                           5863
                           lug                           8903
                           orm                           8150
                           sna                           6585
                           sot                           5963
                           swa                           6248
                           twi                           9336
                           wol                           7806
                           xho                           7166
                           yor                          10801
                           zul                           7027
high_school_microeconomics amh                          17681
                           eng                           5588
                           ewe                          15794
                           fra                           7659
                           hau                          10100
                           ibo                          13353
                           kin                          12384
                           lin                           9293
                           lug                          17315
                           orm                          12167
                           sna                          12487
                           sot                          11117
                           swa                           9817
                           twi                          13293
                           wol                          13784
                           xho                          11694
                           yor                          16425
                           zul                          11626
international_law          amh                          25492
                           eng                           7466
                           ewe                          20548
                           fra                          10834
                           hau                          15221
                           ibo                          16171
                           kin                          17226
                           lin                          12771
                           lug                          19716
                           orm                          16327
                           sna                          14714
                           sot                          13918
                           swa                          13168
                           twi                          17942
                           wol                          18584
                           xho                          16249
                           yor                          20942
                           zul                          15432

llm                                  OpenAI/gpt-4o-2024-08-06  \
subject                    language
elementary_mathematics     amh                          14323
                           eng                           4493
                           ewe                           6951
                           fra                           5078
                           hau                           5753
                           ibo                           5855
                           kin                           5778
                           lin                           5567
                           lug                           6738
                           orm                           6242
                           sna                           5641
                           sot                           5994
                           swa                           5624
                           twi                           6903
                           wol                           6386
                           xho                           5958
                           yor                           7508
                           zul                           6124
global_facts               amh                          18150
                           eng                           4026
                           ewe                           8619
                           fra                           5208
                           hau                           5814
                           ibo                           5870
                           kin                           6502
                           lin                           5760
                           lug                           7309
                           orm                           6342
                           sna                           6220
                           sot                           6117
                           swa                           5531
                           twi                           6693

In [13]:
final.to_csv("token_counts_by_subject_language.csv")

In [11]:
df = pd.concat([pd.read_csv(f) for f in csv_files], ignore_index=True)

# 3) Pivot so rows are 'subject' and columns are each model ('llm'),
#    with the sum of 'num_tokens' as the values
subject_vs_llm = (
    df
    .pivot_table(
        index="subject",
        columns="llm",
        values="num_tokens",
        aggfunc="sum"
    )
    .sort_index()
)

# 4) Inspect it
subject_vs_llm

llm,Anthropic/claude-3-5-sonnet-20241022,CohereLabs/aya-23-35B,Google/gemini-15-Pro-002,OpenAI/gpt-4o-2024-08-06,OpenAI/o1-preview-2024-09-12,Qwen/Qwen2.5-32B,deepseek-ai/DeepSeek-R1,deepseek-ai/DeepSeek-V3-0324,meta-llama/Llama-3.1-405B,microsoft/phi-4,mistralai/Pixtral-12B-2409
subject,,,,,,,,,,,
elementary_mathematics,155346,139818,129890,116916,116916,139378,129987,129987,134886,136398,150502
global_facts,168467,151660,138066,126612,126612,152182,146670,146670,153473,156296,164890
high_school_geography,177291,148527,132774,131205,131205,148592,154270,154270,163635,166514,165184
high_school_microeconomics,284203,249160,221577,215151,215151,248584,258654,258654,271328,276110,271734
international_law,373958,329358,292721,286468,286468,328851,342758,342758,361698,368050,360474

In [12]:
subject_vs_llm.to_csv("subject_vs_llm_token_counts.csv")